common: &common
  adapter: postgresql
  host: localhost
development:
  <<: *common
  database: hackback_dev

test:
  <<: *common
  database: hackback_test

production:
  <<: *common
  database: hackback_prod
